config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: 'homes#top'
  resources :homes, only: [:index, :show]
  resources :projects, only: [:index, :create, :show, :edit, :update, :destroy]
  get '/users/goal' => 'users#goal', as: 'goal'
  resources :users, only: [:update, :show, :edit]
  # get '/projects/all' => 'projects#all'
  # get '/projects/one/:id' => 'projects#one'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  
  attachment :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
   has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    case resource
    when User
      projects_path
    end
  end
  
  def after_sign_up_path_for(resource)
    case resource
    when User
      goal_path
    end
  end
  
  def after_sign_out_path_for(resource)
    case resource
    when :user
      root_path
    end
  end
  
  # def after_sign_out_path_for(resource)
  # リダイレクト先のパス
  # end 

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :number])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
    @projects = Project.all.order(start_time: :desc)
  end
  
  def show
    @project = Project.find(params[:id])
  end
  
  
  def project_params
    params.require(:project).permit(:user_id, :title, :explanation, :image, :start_time)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @user = current_user
    #byebug
    @projects = current_user.projects.order(start_time: :desc)
    
    # ↑後でcurrent_user
    @project = Project.new
    # @tweets = Tweet.all.order(created_at: :desc) #=>新しい順の投稿一覧
  end
  
  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id
    if @project.save
    redirect_to projects_path
    else
      # @project= Project.all
      @user = current_user
      @projects = current_user.projects
      render :index
    end
  end

  def show
    @project = Project.find(params[:id])
    @user = current_user
  end
  
  

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path, notice:"削除しました"
  end

  def edit
    @project = Project.find(params[:id])
    @user = current_user
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to projects_path, notice: "編集しました"
    else
      render 'edit'
    end
  end
  
 
  
  
  
  def project_params
    params.require(:project).permit(:user_id, :title, :explanation, :image, :start_time)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def goal
    @user = current_user
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  # def edit
  #   @project = Project.find(params[:id])
  #   @user = current_user
  # end

  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path
    elsif
      render :edit
    end
  end

  
  protected
  def user_params
    params.require(:user).permit(:goal, :name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.erb
<%= render :partial => "/list" %>

<div class="container">
  <div class="row pt-4">
   <div><p><b>みんなのプロジェクト一覧</b></p></div>
  </div>
  
  <div class="row">
    <% @projects.each do |project| %>
      <div class="col-2 border mx-2 mt-2 pt-2" style="background-color:#ffffff;">
      <%#= link_to home_path do %>
      <%= link_to home_path(project.id) do %>
      <ul style="list-style: none;">
        <li><%= project.start_time.strftime("%y-%m-%d") %></li>
        <li><%= project.user.name %>さん</li>
        <li><%= project.title %></li>
        <li class="mt-3"><%= attachment_image_tag project, :image, size: "75x75", fallback: "no_image.jpg" %></li>
      </ul>
      <% end %>
      </div>
    <% end %>
  </div>
    
    
</div>

app/views/homes/show.html.erb
<%= render :partial => "/list" %>

<p id="notice"><%#= notice %></p>

<div class="container">
  <div class="row" >
    <div class="col-7 mt-3 pt-4 pl-5 pb-4" style="background-color:white;">
      <table>
        <tr>
          <td><%= @project.start_time.strftime("%y-%m-%d") %></td>
          <td></td>
        </tr>
        <tr>
          <td><%= @project.user.name %>さん</td>
          <td></td>
        </tr>
        <tr class="mt-3">
          <td><b>タイトル</b></td>
          <td><b>　<%= @project.title %></b></td>
        </tr>
        <tr>
          <td><b>内容</b></td>
          <td><b>　<%= @project.explanation %></b></td>
        </tr>
      </table>
    </div>
              
    <div class="col-3 mt-3 pt-4">
      <p>
        <!--<strong>写真</strong>-->
        <%#= @project.image %><%= attachment_image_tag @project, :image, size: "100x100", fallback: "no_image.jpg" %>
      </p>
    </div>
      
  </div>


  <div class="row mt-5" style="text:center;">
    <%= link_to '戻る', projects_path, class:'btn btn-success' %>
  </div>
  
</div>

app/views/homes/top.html.erb
<%= render :partial => "/list" %>

<div class="d-flex align-items-center justify-content-center mt-5"><%= link_to 'プロジェクトを始めよう！', new_user_session_path %></div>

<div class="d-flex align-items-center justify-content-center mt-5"><%= image_tag 'start.jpg', size: '400x280'%></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/edit.html.erb
<%= render :partial => "/list" %>
<div class="container">
  
  <div class="row">
    <p>
      <b><%= @user.name %>さん<br>
      <%= @user.goal %></b><br>
      <%#= @projects.id%><%#= current_user.books.where('created_at > ?', Date.today).count %> <br>
      <%#= link_to 'マイプロジェクト一覧', root_path %>
    </p>
  </div>
  
  <div class="row">
    <div class="col-10">
    <%= form_with(model: @project, local: true) do |f| %>
    
      <%#= f.start_time.strftime("%y-%m-%d") %>
      <%= @project.start_time.strftime("%y-%m-%d") %>
      <%#= f.datetime_field :start_time %>
    
      <div class="title">
        <div class="form-tag">タイトル</div>
        <%= f.text_field :title %>
      </div>
      
      <div class="content">
        <div class="form-tag">内容</div>
        <%= f.text_field :explanation %>
      </div>
        <div class="image">
        <div class="form-tag">写真</div>
        <%#= f.attachment_field :image %>
        <%#= attachment_image_tag @project, :image, size: "100x100", fallback: "no_image.jpg" %>
        <%#= f.attachment_field :image, size: "100x120", fallback: "noimage.png" %>
        
        <%= f.attachment_field :image, size: "100x100", fallback: "no_image.jpg"%>
      </div>
      <div class="submit">
        <%= f.submit %>
      </div>
    <% end %>
    </div>
  </div>
  
</div>

app/views/projects/index.html.erb
<%= render :partial => "/list" %>
<div class="container">
  
  <div class="row">
    <p>
      <b><%= @user.name %>さん<br>
      <%= @user.goal %></b><br>
      <%#= @projects.id%><%#= current_user.books.where('created_at > ?', Date.today).count %> <br>
      <%#= link_to 'マイプロジェクト一覧', root_path %>
    </p>
  </div>
  
  <div class="row">
    <!--カレンダー-->
    <div class="col-6 pr-3 pl-3" style="background-color:#ffffff;">
	   <%#= render :partial => "calender", :locals => { projects: @projects, project: @project } %>
      <%= month_calendar events: @projects do |date, projects| %>
        <%= date.day %>
      
        <% projects.each do |project| %>
          <div>
            <%= link_to project.title, project %>
          </div>
        <% end %>
      <% end %>
    </div>
    
    <!--投稿-->
    <div class="col-6 pl-6">
      <%= form_with(model: @project, local: true) do |f| %>
        <div class="time">
          <div class="form-tag">★︎活動日</div>
          <%= f.datetime_field :start_time %>
        </div>
        
        <div class="title mt-2">
          <div class="form-tag">★タイトル</div>
          <%= f.text_field :title, :size => "50*30"%>
        </div>
        
        <div class="content mt-2">
          <div class="form-tag">★内容</div>
          <%= f.text_area :explanation, :size => "50*50" %>
        </div>
        
        <div>
          <div class="form-tag mt-2">★写真</div>
          <%= f.attachment_field :image %>
        </div>

        <div class="submit mt-3 text-right">
          <%= f.submit "投稿する", class:'btn btn-warning' %>
        </div>
      <% end %>
    </div>
  </div>
  
  <div class="row pt-4">
   <div><p><b>マイ・プロジェクト一覧</b></p></div>
  </div>
  <div class="row">
    <% @projects.each do |project| %>
    <div class="col-2 border mx-2 mt-2" style="background-color:#ffffff;">
    <%= link_to project_path(project) do %>
      <ul style="list-style: none;">
        <li><%= project.start_time.strftime("%y-%m-%d") %></li>
        <li><%= project.title %></li>
        <li class="mt-3"><%= attachment_image_tag project, :image, size: "75x75", fallback: "no_image.jpg" %></li>
      </ul>
    <% end %>
    </div>
    <% end %>
  </div>


</div>

app/views/projects/one.html.erb
<%= render :partial => "/list" %>

<p id="notice"><%= notice %></p>
<div class="show">

<div class="container">
  <p>
  <strong>日時</strong>
  <%= @project.start_time.strftime("%m-%d") %>
  </p>

  <p>
    <strong>タイトル</strong>
    <%= @project.title %>
  </p>

  <p>
    <strong>内容</strong>
    <%= @project.explanation %>
  </p>

  <p>
    <strong>写真</strong>
    <%= @project.image %>
  </p>


  <%= link_to '編集', edit_project_path(@project) %>
  <%= link_to '消去',project_path(@project.id), method: :delete, data: { confirm: '本当に?' } %>
  <%= link_to '戻る', projects_path %>
  
</div>

app/views/projects/show.html.erb
<%= render :partial => "/list" %>
<p id="notice"><%= notice %></p>
  
  <div class="container">
    
    <div class="row">
    <p>
      <b><%= @user.name %>さん<br>
      <%= @user.goal %></b>
    </p>
  </div>
  
    <!--投稿内容-->
    <div class="row" >
      <div class="col-7 mt-3 pt-4 pl-5 pb-4" style="background-color:white;">
        
        <table>
          <tr>
            <td><%= @project.start_time.strftime("%y-%m-%d") %></td>
            <td></td>
          </tr>
          <tr>
            <td><b>タイトル</b></td>
            <td><b>　<%= @project.title %></b></td>
          </tr>
          <tr>
            <td><b>内容</b></td>
            <td><b>　<%= @project.explanation %></b></td>
          </tr>
        </table>
      </div>
              
      <div class="col-3 mt-3 pt-4">
        <p>
          <!--<strong>写真</strong>-->
          <%#= @project.image %><%= attachment_image_tag @project, :image, size: "100x100", fallback: "no_image.jpg" %>
        </p>
      </div>
      
    </div>
    
    <!--ボタン-->
    <div class="row mt-5" style="text:center;">
      <!--<div style="text-align:center;">-->
      <div class="mr-1"><%= link_to '編集', edit_project_path(@project), class:'btn btn-primary' %></div>
      <div class="mr-1"><%= link_to '消去',project_path(@project.id), method: :delete, data: { confirm: '本当に?' }, class:'btn btn-danger' %></div>
      <div><%= link_to '戻る', projects_path, class:'btn btn-success' %></div>
      <!--</div>-->
    </div>


</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/edit.html.erb
<%= render :partial => "/list" %>

<p id="notice"><%#= notice %></p>
  
  <div class="container">

    <div class="row" >
      <div class="col-7 mt-3 pt-4 pl-5 pb-4" style="background-color:white;">
      <%= form_with(model: @user, local: true) do |f| %>
        <table>
          <tr>
            <td>名前</td>
            <td>　<%= f.text_field :name %></td>
          </tr>
          <tr>
            <td>目標</td>
            <td>　<%= f.text_field :goal %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td>　<%= f.text_field :email %></td>
          </tr>
        </table>
      
      </div>

    </div>
    
    <!--ボタン-->
    <div class="row mt-5" >
      <!--<div style="text-align:center;">-->
      <div class="mr-1"><%= f.submit "更新", class:'btn btn-warning'%></div>
      <%#= link_to '編集', edit_user_path(@user), class:'btn btn-danger' %>
      <%#= link_to '消去',project_path(@project.id), method: :delete, data: { confirm: '本当に?' }, class:'btn btn-danger' %>
      <div><%= link_to '戻る', user_path, class:'btn btn-success' %></div>
      <!--</div>-->
    </div>
    <% end %>


</div>

app/views/users/goal.html.erb
<%= render :partial => "/list" %>
<p>目標</p>
<%#= form_with model: @user, url: user_path(@user), local: true do |f| %>
<%#= f.text_field :goal %>
<%# end%>

<%= form_with model: @user, url: user_path(@user), local: true do |f| %>
<div style="text-align:center;">
  <%= f.text_area :goal, size: "100x5"%>
</div>

<div class="mt-3", style="text-align:center;">
  <%= f.submit "次へ", class:'btn btn-danger' %>
</div>
  
<% end %>

app/views/users/show.html.erb
<%= render :partial => "/list" %>

<p id="notice"><%#= notice %></p>
  
  <div class="container">

    <div class="row" >
      <div class="col-7 mt-3 pt-4 pl-5 pb-4" style="background-color:white;">
        <table>
          <tr>
            <td>名前</td>
            <td>　<%= @user.name %></td>
          </tr>
          <tr>
            <td>目標</td>
            <td>　<%= @user.goal %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td>　<%= @user.email %></td>
          </tr>
        </table>
      </div>

    </div>
    
    <!--ボタン-->
    <div class="row mt-5", style="text-align:center;">
      <!--<div style="text-align:center;">-->
      <div class="mr-1"><%= link_to '編集', edit_user_path(@user), 'data-turbolinks': false, class:'btn btn-primary' %></div>
      <%#= link_to '消去',project_path(@project.id), method: :delete, data: { confirm: '本当に?' }, class:'btn btn-danger' %>
      <div><%= link_to '戻る', projects_path, class:'btn btn-success' %></div>
      <!--</div>-->
    </div>


</div>